name: Update METF reports

on:
  schedule:
    - cron: '23 09 1 * *'   # runs on the 1st of each month at 09:23 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pdfminer.six

      - name: Update README section
        run: python scripts/update_metf_reports.py

      - name: Commit changes (if any)
        run: |
          if ! git diff --quiet -- README.md; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: refresh METF reports list"
            git push
          else
            echo "No changes to commit."
          fi
